import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { ArrowLeft, CheckCircle2, MessageCircle, UserRound, ClipboardList, Route, Languages, Trash2 } from "lucide-react";
import { api, errorMessage } from "../../lib/api";
import { PageHeader, Section } from "../../components/UI";

const solutions=["TECHNOLOGY_MACHINERY","SOLAR_ENERGY","PRODUCT_DEVELOPMENT","BRANDING_MARKETING","PACKAGING","FINANCING","TRAINING","MARKET_LINKAGE","OTHER"];
const solutionLabels:any={TECHNOLOGY_MACHINERY:"Technology / Machinery",SOLAR_ENERGY:"Solar / Energy",PRODUCT_DEVELOPMENT:"Product Development",BRANDING_MARKETING:"Branding & Marketing",PACKAGING:"Packaging",FINANCING:"Financing",TRAINING:"Training",MARKET_LINKAGE:"Market Linkage",OTHER:"Other"};
const status=(v:any)=>String(v||"—").replaceAll("_"," "); const date=(v:any)=>v?new Date(v).toLocaleString("en-IN",{day:"2-digit",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit"}):"—";
const selectValues=(e:any)=>Array.from(e.target.selectedOptions).map((o:any)=>o.value);

export function ParticipantProfilePage(){
 const{id}=useParams();const[p,setP]=useState<any>(null);const[q,setQ]=useState<any[]>([]);const[wa,setWa]=useState<any[]>([]);const[error,setError]=useState("");const[busy,setBusy]=useState(false);
 useEffect(()=>{if(!id)return;Promise.all([api.get(`/participants/${id}`),api.get("/participant-questions"),api.get(`/whatsapp/participants/${id}/interactions`)]).then(([a,b,c])=>{setP(a.data?.data);setQ(b.data?.data||[]);setWa(c.data?.data||[])}).catch(e=>setError(errorMessage(e)))},[id]);
 const update=(patch:any)=>{setBusy(true);setError("");api.patch(`/participants/${id}`,patch).then(r=>setP(r.data?.data)).catch(e=>setError(errorMessage(e))).finally(()=>setBusy(false))};
 const removeParticipant=async()=>{
   if(!id||!window.confirm(`Delete participant "${p?.name||"this participant"}"? This will soft-delete the record and remove it from active participant lists.`))return;
   setBusy(true);setError("");
   try{await api.delete(`/participants/${id}`);window.location.href="/admin/participants";}
   catch(e){setError(errorMessage(e));setBusy(false)}
 };
 if(error&&!p)return <div className="error">{error}</div>; if(!p)return <div className="empty">Loading participant...</div>;
 const answerMap=new Map((p.answers||[]).map((a:any)=>[String(a.questionId),a.answer]));
 return <div className="participant-profile-page">
  <div className="profile-back"><Link to="/admin/participants"><ArrowLeft size={15}/> Back to participants</Link><span>Participant ID · {String(p._id).slice(-8)}</span></div>
  <PageHeader eyebrow="Participant Profile" title={p.name||"Unnamed participant"} description={`${status(p.participantStatus)} · Registered ${date(p.createdAt)}`} action={<><span className="save-status">{busy ? <><span className="saving-dot"/>Saving…</> : <><CheckCircle2 size={15}/> Up to date</>}</span><button disabled={busy} onClick={()=>void removeParticipant()}><Trash2 size={16}/> Delete participant</button><button className="button-primary" disabled={busy} onClick={()=>api.post(`/whatsapp/participants/${id}/send-post-event`).then(()=>alert("Post-event WhatsApp template queued/sent.")).catch(e=>setError(errorMessage(e)))}><MessageCircle size={16}/> Send post-event WhatsApp</button></>} />
  {error&&<div className="error">{error}</div>}
  <div className="profile-summary"><div className="profile-identity"><div className="profile-avatar"><UserRound size={28}/></div><div><strong>{p.name||"Unnamed"}</strong><span>{p.mobile||"No mobile"}</span><div className="tag-row"><span className="tag green">{p.whatsappAvailable?"WhatsApp available":"WhatsApp unavailable"}</span><span className="tag">{String(p.preferredLanguage||"mr").toUpperCase()}</span></div></div></div><div className="summary-metric"><small>Assessment</small><strong>{status(p.assessmentStatus)}</strong></div><div className="summary-metric"><small>Implementation</small><strong>{status(p.implementationStatus)}</strong></div><div className="summary-metric"><small>Registration</small><strong>{status(p.registrationMethod)}</strong></div></div>

  <Section title="Basic profile" action={<span className="section-note">Captured at registration</span>}><div className="profile-grid">{[["Name",p.name],["Mobile",p.mobile],["Gender",status(p.gender)],["Place",p.location],["Organisation type",status(p.organizationType)],["Organisation",p.organizationName],["Sector",status(p.sector)],["Language",String(p.preferredLanguage||"mr").toUpperCase()],["WhatsApp",p.whatsappAvailable?"Available":"Not available"],["Registered",date(p.createdAt)]].map(([a,b])=><div className="profile-field" key={a as string}><small>{a}</small><b>{b||"—"}</b></div>)}</div></Section>

  <Section title="Post-event requirements" action={<span className="section-note">Update when participant needs are identified</span>}><div className="profile-edit-grid">
   <label><small>Livelihood category</small><select multiple value={p.livelihoodCategories||[]} onChange={e=>update({livelihoodCategories:selectValues(e)})}><option value="AGRICULTURE">Agriculture</option><option value="ANIMAL_HUSBANDRY">Animal Husbandry</option><option value="MICRO_BUSINESS">Micro-business / small business</option><option value="OTHER">Other</option></select></label>
   <label><small>Value chains / interests</small><input defaultValue={(p.valueChains||[]).join(", ")} onBlur={e=>update({valueChains:e.target.value.split(",").map((x:string)=>x.trim()).filter(Boolean)})}/></label>
   <label><small>Support / solutions</small><select multiple value={p.supportSolutions||[]} onChange={e=>update({supportSolutions:selectValues(e)})}>{solutions.map(x=><option key={x} value={x}>{solutionLabels[x]}</option>)}</select></label>
   <label><small>Specific solution / provider</small><input defaultValue={p.specificSolutionProviderInterest||""} onBlur={e=>update({specificSolutionProviderInterest:e.target.value,specificSolutionProviderInterested:Boolean(e.target.value)})}/></label>
   <label><small>Next actions</small><select multiple value={p.nextActions||[]} onChange={e=>update({nextActions:selectValues(e)})}>{[["UNDERSTAND_SOLUTION","Understand solution better"],["SPEAK_TO_PROVIDER","Speak to solution provider"],["GET_COST_ESTIMATE","Get a cost estimate"],["EXPLORE_FINANCING","Explore financing options"],["DISCUSS_IMPLEMENTATION","Discuss implementation"],["OTHER","Other"]].map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>
   <label><small>What was useful</small><select multiple value={p.usefulAtMela||[]} onChange={e=>update({usefulAtMela:selectValues(e)})}>{[["TECHNOLOGIES_MACHINERY","Technologies / machinery showcased"],["SOLAR_ENERGY","Solar / energy solutions"],["SOLUTION_PROVIDERS","Interaction with solution providers"],["SPEAKERS_SESSIONS","Speakers / sessions"],["DEMONSTRATIONS","Demonstrations"],["FINANCING_SUPPORT","Information on financing / support"],["NETWORKING","Networking with other participants"],["OTHER","Other"]].map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label>
   <label className="field-full"><small>What could have been better?</small><textarea rows={4} defaultValue={p.whatCouldBeBetter||""} onBlur={e=>update({whatCouldBeBetter:e.target.value})}/></label>
  </div></Section>

  <Section title="Assessment & implementation" action={<span className="section-note"><ClipboardList size={14}/> Operational tracking</span>}><div className="profile-edit-grid"><label><small>Assessment status</small><select value={p.assessmentStatus||"NOT_STARTED"} onChange={e=>update({assessmentStatus:e.target.value})}><option>NOT_STARTED</option><option>IN_PROGRESS</option><option>COMPLETED</option></select></label><label><small>Implementation status</small><select value={p.implementationStatus||"NOT_STARTED"} onChange={e=>update({implementationStatus:e.target.value})}>{["NOT_STARTED","PLANNED","APPROVED","IN_PROGRESS","IMPLEMENTED","DEFERRED","REJECTED"].map(x=><option key={x}>{x}</option>)}</select></label><label className="field-full"><small>Recommended solutions</small><input defaultValue={(p.recommendedSolutions||[]).join(", ")} onBlur={e=>update({recommendedSolutions:e.target.value.split(",").map((x:string)=>x.trim()).filter(Boolean)})}/></label><label className="field-full"><small>Implementation notes</small><textarea rows={5} defaultValue={p.implementationNotes||""} onBlur={e=>update({implementationNotes:e.target.value})}/></label></div></Section>

  <Section title="Solution journey" action={<span className="section-note"><Route size={14}/> Track each selected solution</span>}><div className="solution-tracks">{(p.solutionTracks||[]).map((track:any,index:number)=><div className="solution-track" key={index}><div className="track-icon"><Route size={17}/></div><div className="track-main"><strong>{solutionLabels[track.solution]||track.solution}</strong><span>{track.requirement||track.valueChain||"Requirement not specified"}</span></div><select value={track.status||"IDENTIFIED"} onChange={e=>{const next=[...(p.solutionTracks||[])];next[index]={...next[index],status:e.target.value,updatedAt:new Date().toISOString()};update({solutionTracks:next})}}>{["IDENTIFIED","RECOMMENDED","MATCHED","PLANNED","IN_PROGRESS","IMPLEMENTED","DEFERRED","REJECTED"].map(x=><option key={x}>{x}</option>)}</select></div>)}{!(p.solutionTracks||[]).length&&<div className="empty">No detailed solution tracks yet. Add support/solutions above and create detailed tracks from the assessment workflow.</div>}</div></Section>

  <Section title="WhatsApp conversation" action={<span className="section-note"><MessageCircle size={14}/> {wa.length} interactions</span>}><div className="whatsapp-journey"><div className="conversation-summary"><div><small>Conversation step</small><strong>{status(p.postEventStep || "NONE")}</strong></div><div><small>WhatsApp status</small><strong>{status(p.whatsappStatus || "PENDING")}</strong></div><div><small>Last interaction</small><strong>{date(p.lastWhatsAppInteractionAt)}</strong></div></div>{wa.length ? <div className="conversation-list">{[...wa].reverse().map((item:any)=><div className={`conversation-message ${String(item.direction||"").toLowerCase()}`} key={item._id}><div><b>{item.direction === "INBOUND" ? "Participant" : item.method === "ADMIN" ? "Admin" : "WhatsApp assistant"}</b><span>{status(item.status)}</span></div><p>{item.message || "—"}</p><small>{date(item.createdAt)}</small></div>)}</div> : <div className="empty">No WhatsApp conversation yet.</div>}</div></Section>

  <Section title="Registration answers" action={<span className="section-note"><Languages size={14}/> Original registration responses</span>}><div className="answers-list">{q.map((question:any)=><div className="answer-row" key={question._id}><div><small>{question.question}</small><span>{question.required?"Required":"Optional"}</span></div><p>{answerMap.get(String(question._id))||"—"}</p></div>)}</div></Section>
 </div>
}
